from .abstract import *
from .adjectives import *
from .adverbs import *
from .articles import *
from .conjunctions import *
from .entities import *
from .factories import *
from .interjections import *
from .nouns import *
from .prepositions import *
from .pronouns import *
from .times import *
from .verbs import *
